import { jsPDF } from 'jspdf';

export class PdfService {
    constructor(private studioName: string, private branding?: { primaryColor?: string; logoUrl?: string }) { }

    async generateReportPdf(reportType: string, data: any, period: { start: string; end: string }): Promise<ArrayBuffer> {
        const doc = new jsPDF();
        const primaryColor = this.branding?.primaryColor || '#111827';

        // Header
        doc.setFillColor(primaryColor);
        doc.rect(0, 0, 210, 40, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.text(this.studioName, 20, 25);

        doc.setFontSize(12);
        const reportTitle = `${reportType.charAt(0).toUpperCase() + reportType.slice(1)} Report`;
        doc.text(reportTitle, 20, 33);

        // Period Info
        doc.setTextColor(107, 114, 128); // #6B7280
        doc.setFontSize(10);
        const start = new Date(period.start).toLocaleDateString();
        const end = new Date(period.end).toLocaleDateString();
        doc.text(`Period: ${start} - ${end}`, 20, 50);
        doc.text(`Generated: ${new Date().toLocaleString()}`, 140, 50);

        // Content based on report type
        let y = 70;
        doc.setTextColor(17, 24, 39); // #111827

        if (reportType === 'revenue') {
            this.addRevenueContent(doc, data, y);
        } else if (reportType === 'attendance') {
            this.addAttendanceContent(doc, data, y);
        } else if (reportType === 'journal') {
            this.addJournalContent(doc, data, y);
        } else {
            this.addCustomContent(doc, data, y);
        }

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(156, 163, 175); // #9CA3AF
        doc.text('Generated by Studio Platform', 105, 285, { align: 'center' });

        return doc.output('arraybuffer');
    }

    private addRevenueContent(doc: jsPDF, data: any, y: number) {
        doc.setFontSize(16);
        doc.text('Key Metrics', 20, y);
        y += 10;

        doc.setFontSize(12);
        doc.text(`Gross Volume: $${(data.grossVolume / 100).toFixed(2)}`, 25, y); y += 8;
        doc.text(`MRR: $${(data.mrr / 100).toFixed(2)}`, 25, y); y += 8;

        y += 10;
        doc.setFontSize(14);
        doc.text('Revenue Breakdown', 20, y);
        y += 10;

        doc.setFontSize(10);
        doc.text(`Retail: $${(data.breakdown.retail / 100).toFixed(2)}`, 25, y); y += 7;
        doc.text(`Class Packs: $${(data.breakdown.packs / 100).toFixed(2)}`, 25, y); y += 7;
        doc.text(`Subscription Renewals: $${(data.breakdown.renewals / 100).toFixed(2)}`, 25, y); y += 7;
    }

    private addAttendanceContent(doc: jsPDF, data: any, y: number) {
        doc.setFontSize(16);
        doc.text('Attendance Overview', 20, y);
        y += 10;

        doc.setFontSize(12);
        doc.text(`Total Bookings: ${data.totalBookings}`, 25, y); y += 8;
        doc.text(`Total Check-ins: ${data.totalCheckins}`, 25, y); y += 8;
        const rate = data.totalBookings > 0 ? ((data.totalCheckins / data.totalBookings) * 100).toFixed(1) : '0';
        doc.text(`Attendance Rate: ${rate}%`, 25, y); y += 15;

        doc.setFontSize(14);
        doc.text('Top Performing Classes', 20, y);
        y += 10;

        doc.setFontSize(10);
        data.topClasses.forEach((cls: any, i: number) => {
            doc.text(`${i + 1}. ${cls.title}: ${cls.attendees} attendees`, 25, y);
            y += 7;
        });
    }

    private addJournalContent(doc: jsPDF, data: any[], y: number) {
        doc.setFontSize(16);
        doc.text('Financial Journal', 20, y);
        y += 15;

        // Table Headers
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text('Date', 20, y);
        doc.text('Description', 45, y);
        doc.text('Account', 100, y);
        doc.text('Debit', 160, y, { align: 'right' });
        doc.text('Credit', 185, y, { align: 'right' });

        y += 5;
        doc.setLineWidth(0.1);
        doc.line(20, y, 190, y);
        y += 8;

        doc.setFont('helvetica', 'normal');
        data.slice(0, 25).forEach(item => { // Limit to avoid overlap for now
            if (y > 270) return; // Basic paging safety
            doc.text(item.date, 20, y);
            const desc = item.description.length > 25 ? item.description.slice(0, 22) + '...' : item.description;
            doc.text(desc, 45, y);
            doc.text(item.account, 100, y);
            if (item.debit > 0) doc.text(item.debit.toFixed(2), 160, y, { align: 'right' });
            if (item.credit > 0) doc.text(item.credit.toFixed(2), 185, y, { align: 'right' });
            y += 7;
        });

        if (data.length > 25) {
            y += 5;
            doc.setFontSize(8);
            doc.setTextColor(107, 114, 128);
            doc.text(`... and ${data.length - 25} more entries. Full list in CSV export.`, 20, y);
        }
    }

    private addCustomContent(doc: jsPDF, data: any, y: number) {
        doc.setFontSize(16);
        doc.text('Report Summary', 20, y);
        y += 15;

        doc.setFontSize(12);
        Object.entries(data.summary).forEach(([key, value]: [string, any]) => {
            const label = key.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
            const val = typeof value === 'number' ? value.toFixed(2) : value;
            doc.text(`${label}: ${val}`, 25, y);
            y += 10;
        });
    }
}
