import { ExpoConfig, ConfigContext } from 'expo/config';
import fs from 'fs';
import path from 'path';

export default ({ config }: ConfigContext): ExpoConfig => {
    // Check for local tenant config (generated by scripts/setup-tenant-mobile.js)
    const configPath = path.join(__dirname, 'tenant.config.json');
    let tenantConfig: any = {};

    if (fs.existsSync(configPath)) {
        try {
            tenantConfig = JSON.parse(fs.readFileSync(configPath, 'utf8'));
            console.log(`📱 Loading tenant config for: ${tenantConfig.name}`);
        } catch (e) {
            console.warn("Failed to parse tenant.config.json", e);
        }
    } else {
        console.log("⚠️ No specific tenant config found, using defaults.");
    }

    const appName = tenantConfig.name || "Studio Platform";
    const appSlug = tenantConfig.slug ? `studio-${tenantConfig.slug}` : "studio-mobile";
    const bundleId = tenantConfig.bundleIdentifier || "com.studio.platform";
    const primaryColor = tenantConfig.primaryColor || "#000000";

    // Use tenant assets if available, else fall back to defaults
    const icon = tenantConfig.iconPath || "./assets/images/icon.png";
    const splashImage = tenantConfig.splashPath || "./assets/images/splash-icon.png";

    return {
        ...config,
        name: appName,
        slug: appSlug,
        version: tenantConfig.version || "1.0.0",
        orientation: "portrait",
        icon: icon,
        scheme: tenantConfig.scheme || "studio-mobile",
        userInterfaceStyle: "automatic",
        newArchEnabled: true,
        splash: {
            image: splashImage,
            resizeMode: "contain",
            backgroundColor: primaryColor
        },
        ios: {
            supportsTablet: true,
            bundleIdentifier: bundleId
        },
        android: {
            package: bundleId,
            adaptiveIcon: {
                foregroundImage: icon, // Use same icon for adaptive for now, or add specific support later
                backgroundColor: primaryColor
            },
            // @ts-expect-error edgeToEdgeEnabled removed from SDK 55 types but still functional
            edgeToEdgeEnabled: true,
            predictiveBackGestureEnabled: false
        },
        web: {
            bundler: "metro",
            output: "static",
            favicon: "./assets/images/favicon.png"
        },
        plugins: [
            "expo-router",
            [
                "expo-notifications",
                {
                    "icon": "./assets/images/notification-icon.png",
                    "color": primaryColor
                }
            ]
        ],
        experiments: {
            typedRoutes: true
        },
        extra: {
            tenantSlug: tenantConfig.slug,
            apiUrl: tenantConfig.apiUrl || process.env.API_URL || "https://studio-platform-api.slichti.workers.dev",
            eas: {
                projectId: "your-project-id" // You might need to make this dynamic if multiple EAS projects
            }
        }
    };
};
